apiVersion: v1
kind: Namespace
metadata:
  name: pokeproxy
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: pokeproxy
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
