{{- $fullname := include "pokeproxy.component.fullname" (dict "context" $ "component" "pokeproxy") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullname }}-hmac
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pokeproxy.component.labels" (dict "context" $ "component" "pokeproxy") | nindent 4 }}
spec:
  encryptedData:
    POKEPROXY_HMAC_KEY: {{ .Values.hmac.encryptedValue | quote }}
  template:
    metadata:
      name: {{ $fullname }}-hmac
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "pokeproxy.component.labels" (dict "context" $ "component" "pokeproxy") | nindent 8 }}
    type: Opaque
