{{- $spec := .Values.components.pokeproxy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokeproxy.component.fullname" (dict "context" $ "component" "pokeproxy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pokeproxy.component.labels" (dict "context" $ "component" "pokeproxy") | nindent 4 }}
spec:
  selector:
    {{- include "pokeproxy.component.selectorLabels" (dict "context" $ "component" "pokeproxy") | nindent 4 }}
  ports:
    - name: http
      port: {{ $spec.port }}
      targetPort: http
