{{- $spec := .Values.components.pokeproxy }}
{{- if and $spec.enabled .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pokeproxy.component.fullname" (dict "context" $ "component" "pokeproxy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pokeproxy.component.labels" (dict "context" $ "component" "pokeproxy") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pokeproxy.component.selectorLabels" (dict "context" $ "component" "pokeproxy") | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
{{- end }}
