{{- range $component, $spec := .Values.components }}
{{- if and $spec.enabled $spec.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pokeproxy.component.fullname" (dict "context" $ "component" $component) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "pokeproxy.component.labels" (dict "context" $ "component" $component) | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
